#!/usr/bin/env bash
# freshness.sh - Detects whether a context pack went stale relative to the code.
#
# Each pack (skill with `generado_desde:` frontmatter) declares from which
# state of each repo it was written: short git commit, or snapshot fingerprint
# for repos without .git (stamp_of_repo from repo-lib.sh). This script compares
# those stamps against the CURRENT state of repos/.
#
# USAGE
#   scripts/freshness.sh check             # all packs; rc=1 if any is stale
#   scripts/freshness.sh check <pack>      # only that pack (skill name)
#   scripts/freshness.sh seal <pack>       # re-stamps the pack to the current state
#   (comprobar/sellar remain as compatibility aliases)
#                                          # (ONLY after re-verifying its content)
# Compatible with bash 3.2 (macOS).
set -uo pipefail
cd "$(dirname "$0")/.."
. scripts/repo-lib.sh

MODE="${1:-check}"
case "${MODE}" in comprobar) MODE="check" ;; sellar) MODE="seal" ;; esac
PACK_ARG="${2:-}"

pack_files() {
  if [ -n "${PACK_ARG}" ]; then
    if [ ! -f ".claude/skills/${PACK_ARG}/SKILL.md" ]; then
      echo "ERROR - skill '${PACK_ARG}' does not exist" >&2; return 1
    fi
    echo ".claude/skills/${PACK_ARG}/SKILL.md"
  else
    grep -l '^generado_desde:' .claude/skills/*/SKILL.md 2>/dev/null || true
  fi
}

# Prints "repo stamp" per line from the pack's frontmatter
stamps_of_pack() {
  awk '
    /^generado_desde:/ { f=1; next }
    f && /^[^ ]/ { f=0 }
    f && /^  [A-Za-z0-9._-]+:/ {
      gsub(/[:#].*$/, "", $1); stamp=$2; sub(/#.*/, "", stamp)
      print $1, stamp
    }
  ' "$1" | sed 's/:$//'
}

case "${MODE}" in
  check)
    FILES=$(pack_files) || exit 2
    if [ -z "${FILES}" ]; then
      echo "No packs with 'generado_desde:' - nothing to check."
      echo "(they are generated by /repo-map and /system-map)"
      exit 0
    fi
    RC=0
    for f in ${FILES}; do
      pack=$(basename "$(dirname "${f}")")
      CADUCO=""
      while IFS=' ' read -r repo sello; do
        [ -z "${repo}" ] && continue
        if [ ! -e "repos/${repo}" ]; then
          echo "  ?         ${pack}: repos/${repo} is not present (setup.sh)"
          continue
        fi
        actual=$(stamp_of_repo "${repo}")
        if [ "${actual}" != "${sello}" ]; then
          CADUCO="si"
          echo "  STALE     ${pack}: ${repo} ${sello} -> ${actual}"
        fi
      done <<EOF
$(stamps_of_pack "${f}")
EOF
      if [ -z "${CADUCO}" ]; then
        echo "  fresh     ${pack}"
      else
        RC=1
      fi
    done
    if [ "${RC}" -ne 0 ]; then
      echo ""
      echo "STALE packs: regenerate them with /repo-map or /system-map"
      echo "(re-verify the content; then scripts/freshness.sh seal <pack>)."
    fi
    exit "${RC}" ;;
  seal)
    if [ -z "${PACK_ARG}" ]; then echo "usage: $0 seal <pack>"; exit 2; fi
    FILES=$(pack_files) || exit 2
    f="${FILES}"
    TMPF=$(mktemp)
    stamps_of_pack "${f}" | while IFS=' ' read -r repo _old; do
      [ -z "${repo}" ] && continue
      if [ -e "repos/${repo}" ]; then
        printf '%s %s\n' "${repo}" "$(stamp_of_repo "${repo}")"
      fi
    done > "${TMPF}"
    python3 - "${f}" "${TMPF}" <<'PY'
import re, sys
path, stamps_file = sys.argv[1], sys.argv[2]
stamps = dict(line.split() for line in open(stamps_file) if line.strip())
out, in_block = [], False
for line in open(path):
    if line.startswith("generado_desde:"):
        in_block = True
        out.append(line)
        continue
    if in_block and not line.startswith("  "):
        in_block = False
    if in_block:
        m = re.match(r"^(  )([A-Za-z0-9._-]+):\s*(\S+)(.*)$", line.rstrip("\n"))
        if m and m.group(2) in stamps:
            line = f"{m.group(1)}{m.group(2)}: {stamps[m.group(2)]}{m.group(4)}\n"
    if line.startswith("verificado:"):
        import datetime
        line = f"verificado: {datetime.date.today().isoformat()}\n"
    out.append(line)
open(path, "w").write("".join(out))
print(f"stamped: {path}")
PY
    rm -f "${TMPF}" ;;
  *)
    echo "usage: $0 comprobar [pack] | sellar <pack>"; exit 2 ;;
esac
